# Generated by Django 6.0 on 2026-05-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_invoice_notificationdispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
