# Generated by Django 5.2.14 on 2026-06-18 08:04

import trekking_and_tour_management_system.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20, validators=[trekking_and_tour_management_system.core.validators.validate_phone_number])),
                ('experience', models.TextField()),
                ('languages', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
