# Generated by Django 5.2.14 on 2026-06-14 04:32

import trekking_and_tour_management_system.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[trekking_and_tour_management_system.core.validators.validate_phone_number]),
        ),
    ]
