# Generated by Django 5.2.14 on 2026-05-31 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='created_from_application',
        ),
    ]
