# Generated by Django 5.2.14 on 2026-05-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_guide_delete_guideprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='address',
        ),
    ]
