# Generated by Django 5.2.14 on 2026-06-26 08:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='packages_ca_slug_e3191c_idx'), models.Index(fields=['name'], name='packages_ca_name_beccfa_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrekPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('destination', models.CharField(db_index=True, max_length=255)),
                ('duration', models.PositiveIntegerField(help_text='Duration in days', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('guide_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MODERATE', 'Moderate'), ('HARD', 'Hard')], db_index=True, default='EASY', max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='packages/images/')),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('available', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='packages.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrekPackageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_point', models.TextField()),
                ('required_items', models.TextField()),
                ('emergency_contact', models.CharField(max_length=100)),
                ('guide_notes', models.TextField(blank=True, null=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='packages.trekpackage')),
            ],
        ),
        migrations.AddIndex(
            model_name='trekpackage',
            index=models.Index(fields=['slug'], name='packages_tr_slug_c9a5b7_idx'),
        ),
        migrations.AddIndex(
            model_name='trekpackage',
            index=models.Index(fields=['available'], name='packages_tr_availab_152741_idx'),
        ),
        migrations.AddIndex(
            model_name='trekpackage',
            index=models.Index(fields=['featured'], name='packages_tr_feature_bfaaf0_idx'),
        ),
        migrations.AddIndex(
            model_name='trekpackageinfo',
            index=models.Index(fields=['emergency_contact'], name='packages_tr_emergen_ac8792_idx'),
        ),
    ]
