# Generated by Django 5.2.14 on 2026-05-31 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrekPackageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_point', models.TextField()),
                ('required_items', models.TextField()),
                ('emergency_contact', models.CharField(max_length=100)),
                ('guide_notes', models.TextField(blank=True, null=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='packages.trekpackage')),
            ],
        ),
    ]
