# Generated by Django 5.2.14 on 2026-06-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_trekpackageinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trekpackage',
            name='guide_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
