# Generated by Django 6.0 on 2026-06-10 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contactsupport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSupport',
        ),
    ]
