# Generated by Django 6.0 on 2026-05-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_cancellationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='refund_amount',
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='CancellationRequest',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
