# Generated by Django 5.2.14 on 2026-05-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('guide', 'Guide'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
