# Generated by Django 5.2.14 on 2026-05-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideapplication',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
