# Generated by Django 5.2.14 on 2026-05-24 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide_applications', '0002_guideapplication_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideapplication',
            name='address',
        ),
    ]
