# Generated by Django 5.2.14 on 2026-05-24 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide_applications', '0003_remove_guideapplication_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideapplication',
            name='updated_at',
        ),
    ]
