# Generated by Django 5.2.14 on 2026-05-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_applications', '0004_remove_guideapplication_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideapplication',
            name='account_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guideapplication',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
