# Generated by Django 5.2.14 on 2026-05-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_guide_status_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guide_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='guide_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
