# Generated by Django 5.2.14 on 2026-06-01 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_cancellation_reason_booking_cancelled_at'),
        ('bookings', '0005_booking_guide_assigned_at_booking_guide_responded_at'),
    ]

    operations = [
    ]
