# Generated by Django 5.2.14 on 2026-06-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_guide_price_booking_need_guide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guide_response_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guide_status',
            field=models.CharField(choices=[('NOT_ASSIGNED', 'Not Assigned'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='NOT_ASSIGNED', max_length=20),
        ),
    ]
