# Generated by Django 5.2.14 on 2026-06-14 04:32

import trekking_and_tour_management_system.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[trekking_and_tour_management_system.core.validators.validate_rating]),
        ),
    ]
