# Generated by Django 6.0 on 2026-06-10 03:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_unique_together_review_booking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'package')},
        ),
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
    ]
